name: Java CI - Spring Boot

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest  # or windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: List directory contents
      run: ls -la ./SpringSator  # Adjust this path if necessary

    - name: Build with Maven
      run: mvn clean verify
      working-directory: ./SpringSator  # Adjust this path if necessary

    # Step 4: Upload test results (for review)
    - name: Publish test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          target/surefire-reports/
          target/failsafe-reports/